dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: lu+N0zJJOkhteu+/+TLhAj6jArzZAtxjdiGazazRPS8r5JTBHV0A4hj7AV5kupdwvDtNqZ4xJlwjL+xd65Qd8RhMHAHOIjxl0nEWjWuxQX8N1PfjKV3LvnTxPBRPQ1kBUQ6KvcfhS9mkZPFQBgXcPiQz1FBnhgt+1Vz9ZsCbqbMvqPJ0lu3ezcJdPr7D0Qc9AEY8TcvEtG3UnuotJ16IxT7UAMG9JmF6XOW4b3nXm9oIgkNfA6CNm/ExgNKt6lBsnssePBzoytvJMv/L6tmOZ+jmPFqqrdb4sfrurbZBDOVilz+oyQF+qkgdoCWbQpRIQqxL62A8Wq1WTiZAR6BkhSSn7ttQV7MMq3V5Hfi1rPapLJ8RYNFtbfL0/Mrz8QSQ/HTyr0j2aSoHoLisdcZhYkbphx1VSCm5I4dvRhR+aR7n2bpmVyEe6E6OUXW6XSjqSnwcLqxOperkPCx3xcnWF4YdU2o+/N0Md7/3GDtnD7Bk53gwh1Cb1UqMqtB4j77iACBoz+R54wlhOKCiJdfm7kMu+KroRG4Sn5UCdXzy8NIbRQjSeqwmsXuQITZPt57VU1ZKybbGp386uRXyTp8Nvzo/4RjY7V8ZwmZc6S6pc9hjaG+cJ43myy9RgZSVGJxIylaxJiavmdPDVPmx/bA3Hysp5gitHLaEmR4j58zD8kQ=
